# Generated by Django 3.2.9 on 2021-12-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
